import os
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
import tensorflow as tf
from tensorflow.keras.layers import Input, Conv1D, MaxPooling1D, Bidirectional, LSTM, Dense, Dropout, Attention, GlobalAveragePooling1D

# ==========================================
# Module 7: Automated Clinical Report Generation
# ==========================================

classes = {
    0: ("Normal Beat (N)", "Low Risk", "No immediate action required. Rhythm is stable."),
    1: ("Supraventricular Ectopic (S)", "Medium Risk", "Monitor patient for recurrent ectopic beats."),
    2: ("Ventricular Ectopic (V)", "High Risk", "Immediate cardiology consult required. High risk of V-Fib."),
    3: ("Fusion Beat (F)", "Medium-High Risk", "Atypical waveform fusion detected. Recommend Holter monitor."),
    4: ("Unknown / Paced (Q)", "Variable Risk", "Unclassifiable beat. Verify pacemaker function if applicable.")
}

def load_ai_model(model_path):
    inputs = Input(shape=(216, 1))
    x = Conv1D(filters=64, kernel_size=5, activation='relu', padding='same')(inputs)
    x = MaxPooling1D(pool_size=2)(x)
    x = Conv1D(filters=128, kernel_size=3, activation='relu', padding='same')(x)
    x = MaxPooling1D(pool_size=2)(x)
    x = Dropout(0.2)(x)
    x = Bidirectional(LSTM(64, return_sequences=True))(x)
    attention_out = Attention()([x, x])
    x = GlobalAveragePooling1D()(attention_out)
    x = Dense(64, activation='relu')(x)
    x = Dropout(0.3)(x)
    outputs = Dense(5, activation='softmax')(x)
    
    model = tf.keras.models.Model(inputs=inputs, outputs=outputs)
    model.load_weights(model_path)
    return model

def generate_pdf_report(patient_id, beat_signal, model, save_dir):
    """Generates an official-looking medical report using matplotlib."""
    # Predict
    input_data = beat_signal.reshape(1, 216, 1)
    predictions = model.predict(input_data)[0]
    pred_idx = np.argmax(predictions)
    confidence = predictions[pred_idx] * 100
    diagnosis, risk, advice = classes[pred_idx]
    
    # Create Figure
    fig = plt.figure(figsize=(10, 12))
    fig.patch.set_facecolor('#ffffff')
    
    # Header
    plt.text(0.5, 0.95, "CARDIAC DIAGNOSTIC REPORT", fontsize=24, fontweight='bold', ha='center', color='darkblue')
    plt.text(0.5, 0.92, "Generated by AI Arrhythmia Detection System", fontsize=12, ha='center', color='gray')
    plt.axhline(y=0.90, xmin=0.05, xmax=0.95, color='black', linewidth=2)
    
    # Patient Info
    plt.text(0.1, 0.85, f"Patient ID: {patient_id}", fontsize=14, fontweight='bold')
    plt.text(0.1, 0.82, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", fontsize=12)
    plt.text(0.1, 0.79, f"Scanning Modality: AI-Assisted ECG", fontsize=12)
    
    # Diagnosis Box
    plt.text(0.1, 0.70, "1. AI DIAGNOSIS SUMMARY", fontsize=16, fontweight='bold', color='darkred')
    plt.text(0.15, 0.66, f"Primary Finding: {diagnosis}", fontsize=14)
    plt.text(0.15, 0.63, f"Confidence Score: {confidence:.2f}%", fontsize=14)
    plt.text(0.15, 0.60, f"Risk Stratification: {risk}", fontsize=14, fontweight='bold', 
             color='red' if 'High' in risk else ('orange' if 'Medium' in risk else 'green'))
    
    # ECG Graph inside the report
    plt.text(0.1, 0.52, "2. ECG SIGNAL TRACING (0.6s Window)", fontsize=16, fontweight='bold', color='darkblue')
    
    ax_graph = fig.add_axes([0.15, 0.28, 0.7, 0.22]) # [left, bottom, width, height]
    ax_graph.plot(beat_signal, color='black', linewidth=1.5)
    ax_graph.grid(True, linestyle=':', color='pink')
    ax_graph.set_facecolor('#fffcfc') # slight red tint like real ECG paper
    
    # Medical Advice
    plt.text(0.1, 0.20, "3. CLINICAL RECOMMENDATION", fontsize=16, fontweight='bold', color='darkred')
    plt.text(0.15, 0.16, advice, fontsize=14, style='italic')
    
    # Footer Signatures
    plt.axhline(y=0.08, xmin=0.05, xmax=0.95, color='black', linewidth=1)
    plt.text(0.15, 0.05, "Dr. _______________\nAttending Cardiologist", fontsize=12)
    plt.text(0.65, 0.05, "CNN-BiLSTM-Attention\nAutomated AI Signature", fontsize=12, color='gray')
    
    plt.axis('off')
    
    # Save as PDF
    output_path = os.path.join(save_dir, f"Medical_Report_Patient_{patient_id}.pdf")
    plt.savefig(output_path, format='pdf', bbox_inches='tight')
    plt.close()
    print(f"[SUCCESS] Clinical Report PDF Generated: {output_path}")

if __name__ == "__main__":
    print("\n--- STARTING MODULE 7: AUTOMATED REPORT GENERATION ---")
    results_dir = 'results'
    if not os.path.exists(results_dir):
        os.makedirs(results_dir)
        
    print("Loading Model...")
    model = load_ai_model('models/enhanced_arrhythmia_model.h5')
    
    print("Loading Data...")
    try:
        beats = np.load('data/processed_beats.npy')
        sample_beat = beats[45] if len(beats) > 45 else beats[0]
        
        # Generate the report
        generate_pdf_report(patient_id="PT-88204", beat_signal=sample_beat, model=model, save_dir=results_dir)
    except FileNotFoundError:
        print("[ERROR] Run Module 1 first to generate data.")
